spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:eventbooking}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis

jwt:
  secret: "6f92018d4f5d2a2cbd67a1f24f315e0f67495807b921f95f0a2c342c7291d0d9"

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
